<template><el-form  label-width="100px" size="mini">
    <div class="search-form">
    <el-form-item label="申请单编号"><el-input v-model="requestNo"@keyup.enter.native="handleSearch"clearable></el-input> </el-form-item> <el-form-item label="CR号"><el-input v-model="crNo"@keyup.enter.native="handleSearch"clearable></el-input> </el-form-item> <el-form-item label="主题"><el-input v-model="subject"@keyup.enter.native="handleSearch"clearable></el-input> </el-form-item> <el-form-item label="当前节点"><el-input v-model="activityCnDisplayname"@keyup.enter.native="handleSearch"clearable></el-input> </el-form-item> <el-form-item label="起草人"><el-input v-model="drafterName"@keyup.enter.native="handleSearch"clearable></el-input> </el-form-item> <el-form-item label="平台"><el-input v-model="architecture"@keyup.enter.native="handleSearch"clearable></el-input> </el-form-item> <el-form-item label="项目"><el-input v-model="program"@keyup.enter.native="handleSearch"clearable></el-input> </el-form-item> <el-form-item label="申请类型"><el-select v-model="source"@keyup.enter.native="handleSubmit"clearable> <el-option key="0" label="Local CR" value="Local CR"></el-option> <el-option key="1" label="Global CR" value="Global CR"></el-option></el-select> </el-form-item> <el-form-item label="操作时间"><el-input v-model="operationTime"@keyup.enter.native="handleSubmit"clearable></el-input> </el-form-item> 
     </div>
     <el-row :gutter="0">
     <el-col :span="24" style="text-align:center">
       <el-button @click="handleSearch" size="mini" type="primary">搜索</el-button>
       <el-button @click="handleReset" size="mini">重置</el-button>
     </el-col>
   </el-row>
    </el-form></template><script>
    import { mapState, mapGetters, mapMutations, mapActions } from "vuex";
    export default {computed:{requestNo: {            get: function() {                return this.form.requestNo            },            set: function(val) {                this.setFormByKey({requestNo:val})            }        },crNo: {            get: function() {                return this.form.crNo            },            set: function(val) {                this.setFormByKey({crNo:val})            }        },subject: {            get: function() {                return this.form.subject            },            set: function(val) {                this.setFormByKey({subject:val})            }        },activityCnDisplayname: {            get: function() {                return this.form.activityCnDisplayname            },            set: function(val) {                this.setFormByKey({activityCnDisplayname:val})            }        },drafterName: {            get: function() {                return this.form.drafterName            },            set: function(val) {                this.setFormByKey({drafterName:val})            }        },architecture: {            get: function() {                return this.form.architecture            },            set: function(val) {                this.setFormByKey({architecture:val})            }        },program: {            get: function() {                return this.form.program            },            set: function(val) {                this.setFormByKey({program:val})            }        },source: {            get: function() {                return this.form.source            },            set: function(val) {                this.setFormByKey({source:val})            }        },operationTime: {            get: function() {                return this.form.operationTime            },            set: function(val) {                this.setFormByKey({operationTime:val})            }        },mapState:...mapState('rbntest',['form','pageSize','pageNum','pageTotal','sortType','orderBy','sortDefault','tableData'])},methods:{handleSearch:function() {                this.setByKey({                    pageNum: 1                  });                this.$parent.$refs.customTable.$emit('setCurrentPage', 1);                this.asyncSetTableData()            },handleReset:function() {                this.resetForm();                this.setByKey({                    pageNum: 1                });                this.$parent.$refs.customTable.$emit('setCurrentPage', 1);                this.asyncSetTableData();            },handleSubmit:function() {},mapMutations:...mapMutations('rbntest',['setFormByKey','setByKey','resetForm']),mapActions:...mapActions('rbntest', ['asyncSetTableData'])},mounted:function(){this.asyncSetTableData();}} 
    </script>